// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.MigrationsSqlServer
{
    [DbContext(typeof(SqlServerDbContext))]
    [Migration("20260217175829_RemoveFee")]
    partial class RemoveFee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Models.Journal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("During")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Post")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("First")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Forth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Second")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Third")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Models.SampleSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ReviewId")
                        .HasColumnType("int");

                    b.Property<int>("SampleSizeType")
                        .HasColumnType("int");

                    b.Property<int>("Strategy")
                        .HasColumnType("int");

                    b.Property<int>("TimeFrame")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("SampleSizes");
                });

            modelBuilder.Entity("Models.Trades.BaseTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<double?>("EntryPrice")
                        .HasColumnType("float");

                    b.Property<double?>("ExitPrice")
                        .HasColumnType("float");

                    b.Property<int?>("JournalId")
                        .HasColumnType("int");

                    b.Property<double?>("MaxPrice")
                        .HasColumnType("float");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<double?>("PnL")
                        .HasColumnType("float");

                    b.Property<int>("SampleSizeId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("ScreenshotsUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double?>("StopPrice")
                        .HasColumnType("float");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TradeRating")
                        .HasColumnType("int");

                    b.Property<double?>("TriggerPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.HasIndex("SampleSizeId");

                    b.ToTable("BaseTrades", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AccountSize")
                        .HasColumnType("float");

                    b.Property<double>("ExchSizeLimit")
                        .HasColumnType("float");

                    b.Property<double>("MaxSlippage")
                        .HasColumnType("float");

                    b.Property<int>("PTStrategy")
                        .HasColumnType("int");

                    b.Property<int>("PTTimeFrame")
                        .HasColumnType("int");

                    b.Property<double>("ScaleOut")
                        .HasColumnType("float");

                    b.Property<double>("TradeFee")
                        .HasColumnType("float");

                    b.Property<double>("TradeRisk")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("Models.Trades.BrunchBreak", b =>
                {
                    b.HasBaseType("Models.Trades.BaseTrade");

                    b.Property<int>("CandleType")
                        .HasColumnType("int");

                    b.Property<bool>("IsFlippedTheSwitch")
                        .HasColumnType("bit");

                    b.ToTable("BrunchBreak", (string)null);
                });

            modelBuilder.Entity("Models.Trades.ResearchCandleBracketing", b =>
                {
                    b.HasBaseType("Models.Trades.BaseTrade");

                    b.Property<int>("ATR")
                        .HasColumnType("int");

                    b.Property<double>("CandleHigh")
                        .HasColumnType("float");

                    b.Property<double>("CandleLow")
                        .HasColumnType("float");

                    b.Property<int>("CandleType")
                        .HasColumnType("int");

                    b.Property<double>("EntryPriceForResearch")
                        .HasColumnType("float");

                    b.Property<double>("ExitPriceForResearch")
                        .HasColumnType("float");

                    b.Property<double>("HighestPointAfterEntry")
                        .HasColumnType("float");

                    b.Property<bool>("IsFlippedTheSwitch")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLoss")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWeekend")
                        .HasColumnType("bit");

                    b.Property<double>("LowestPointAfterEntry")
                        .HasColumnType("float");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.ToTable("ResearchCandleBracketing", (string)null);
                });

            modelBuilder.Entity("Models.Trades.ResearchCradle", b =>
                {
                    b.HasBaseType("Models.Trades.BaseTrade");

                    b.Property<int>("TestCradleProp")
                        .HasColumnType("int");

                    b.ToTable("ResearchCradles", (string)null);
                });

            modelBuilder.Entity("Models.Trades.ResearchFirstBarPullback", b =>
                {
                    b.HasBaseType("Models.Trades.BaseTrade");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FullATRMarketGaveSmth")
                        .HasColumnType("bit");

                    b.Property<int>("FullATRMaxRR")
                        .HasColumnType("int");

                    b.Property<int>("FullATROneToOneHitOn")
                        .HasColumnType("int");

                    b.Property<bool>("Is4HTrending")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBreakeven")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDTrending")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEntryAfter3To5Bars")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEntryAfter5Bars")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEntryAfteriBar")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEntryAtPreviousSwingOnTrigger")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEntryBeforePreviousSwingOn4H")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEntryBeforePreviousSwingOnD")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEntryBeforePreviousSwingOnTrigger")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFullATRBreakeven")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFullATRLoss")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFullATROneToFiveHit")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFullATROneToThreeHit")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMomentumTrade")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOneToFiveHit")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOneToThreeHit")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSignalBarInTradeDirection")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSignalBarStrongReversal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTrendTrade")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTriggerTrending")
                        .HasColumnType("bit");

                    b.Property<bool>("MarketGaveSmth")
                        .HasColumnType("bit");

                    b.Property<int>("MaxRR")
                        .HasColumnType("int");

                    b.Property<int>("OneToOneHitOn")
                        .HasColumnType("int");

                    b.ToTable("ResearchFirstBarPullbacks", (string)null);
                });

            modelBuilder.Entity("Models.Trades.SRS", b =>
                {
                    b.HasBaseType("Models.Trades.BaseTrade");

                    b.Property<int>("CandleType")
                        .HasColumnType("int");

                    b.Property<bool>("IsFlippedTheSwitch")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInOverNightRange")
                        .HasColumnType("bit");

                    b.ToTable("SRS", (string)null);
                });

            modelBuilder.Entity("Models.Trades.Trade", b =>
                {
                    b.HasBaseType("Models.Trades.BaseTrade");

                    b.Property<int?>("ResearchId")
                        .HasColumnType("int");

                    b.HasIndex("ResearchId");

                    b.ToTable("Trades", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.SampleSize", b =>
                {
                    b.HasOne("Models.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Models.Trades.BaseTrade", b =>
                {
                    b.HasOne("Models.Journal", "Journal")
                        .WithMany()
                        .HasForeignKey("JournalId");

                    b.HasOne("Models.SampleSize", "SampleSize")
                        .WithMany()
                        .HasForeignKey("SampleSizeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Journal");

                    b.Navigation("SampleSize");
                });

            modelBuilder.Entity("Models.Trades.BrunchBreak", b =>
                {
                    b.HasOne("Models.Trades.BaseTrade", null)
                        .WithOne()
                        .HasForeignKey("Models.Trades.BrunchBreak", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Trades.ResearchCandleBracketing", b =>
                {
                    b.HasOne("Models.Trades.BaseTrade", null)
                        .WithOne()
                        .HasForeignKey("Models.Trades.ResearchCandleBracketing", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Trades.ResearchCradle", b =>
                {
                    b.HasOne("Models.Trades.BaseTrade", null)
                        .WithOne()
                        .HasForeignKey("Models.Trades.ResearchCradle", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Trades.ResearchFirstBarPullback", b =>
                {
                    b.HasOne("Models.Trades.BaseTrade", null)
                        .WithOne()
                        .HasForeignKey("Models.Trades.ResearchFirstBarPullback", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Trades.SRS", b =>
                {
                    b.HasOne("Models.Trades.BaseTrade", null)
                        .WithOne()
                        .HasForeignKey("Models.Trades.SRS", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Trades.Trade", b =>
                {
                    b.HasOne("Models.Trades.BaseTrade", null)
                        .WithOne()
                        .HasForeignKey("Models.Trades.Trade", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Trades.ResearchFirstBarPullback", "Research")
                        .WithMany()
                        .HasForeignKey("ResearchId");

                    b.Navigation("Research");
                });
#pragma warning restore 612, 618
        }
    }
}
